### PR TITLE
Split psnr and apsnr

### LINKED ISSUE #31: Split psnr and apsnr
To maintain the consistency with the other metrics, it would be useful to remove the `PsnrResults` struct and return two different `PlanarMetrics` for the `psnr` and `apsnr` metrics

### PR DESCRIPTION
**Pull request by Luni-4**
This PR fixes #31 

Thanks in advance for your review! :)

### CODE REVIEW

**Comment by shssoichiro** [comment]
Overall I think this makes sense. The only downside is that the PSNR computations are now duplicated. But that problem already exists between SSIM/MSSSIM, so there will need to be some other solution there that can cover both cases (caching perhaps?).

**Comment by lu-zero** [comment]
We can consider memoizing, but I guess it might be overkill.

**Comment by Luni-4** [comment]
Thanks to both of you for landing this PR! :)

> Overall I think this makes sense. The only downside is that the PSNR computations are now duplicated. But that problem already exists between SSIM/MSSSIM, so there will need to be some other solution there that can cover both cases (caching perhaps?). Also PSNR is very fast, so it's not much of a problem here.

I thought the same, but could this problem be solved if `psnr` and `apsnr` are calculated in parallel? Since they are very fast I don't think that a parallel computation might be overkill. The same goes for the `ssim` and `msssim`. What do you think about that @lu-zero  and @shssoichiro?

**Comment by shssoichiro** [comment]
That is a possibility, and should be pretty easy now that async/await is stable.

**Comment by Luni-4** [comment]
@shssoichiro 

I agree, we could open an issue about that

**Pull request merged**
