### PR TITLE
Crude multi-thread support using rayon

### PR DESCRIPTION
**Pull request by lu-zero**
It is _nearly_ an experiment. Help with benchmarking it welcome.

### CODE REVIEW

**Comment by lu-zero** [comment]
```
SSIM                    time:   [18.495 ms 18.579 ms 18.674 ms]
                        change: [-24.998% -24.270% -23.586%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high severe

MSSSIM                  time:   [18.750 ms 18.831 ms 18.921 ms]
                        change: [-30.658% -30.158% -29.684%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

CIEDE2000               time:   [6.8651 ms 7.0149 ms 7.1764 ms]
                        change: [-83.469% -83.099% -82.661%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild

CIEDE2000 #2            time:   [7.4184 ms 7.4604 ms 7.5050 ms]
                        change: [-82.477% -82.317% -82.141%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
  2 (2.00%) low mild
  4 (4.00%) high mild
  1 (1.00%) high severe
```

**Comment by lu-zero** [comment]
reworking the decoder abstraction to process a batch of frames at time might be beneficial.

**Review by shssoichiro — APPROVED** [review]
Impressive

**Comment by lu-zero** [comment]
Ideally I'd make each of the metric take a rayon pool if provided and make so it is shared, another set makes so you can run the different metrics in parallel using [bus](https://crates.io/crates/bus) and yet another would rework the decoder trait/machinery so the metrics system would just consume a channel feeding in N workers in parallel.

(I want this to be as fast as possible on every platform)

**Comment by lu-zero** [comment]
Now a little polished.

```
PSNR yuv420p8           time:   [166.98 us 167.56 us 168.36 us]
                        change: [-13.665% -12.037% -10.486%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 11 outliers among 100 measurements (11.00%)
  5 (5.00%) high mild
  6 (6.00%) high severe

PSNR-HVS yuv420p8       time:   [3.8200 ms 3.9287 ms 4.0482 ms]
                        change: [-27.727% -25.634% -22.843%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 18 outliers among 100 measurements (18.00%)
  6 (6.00%) high mild
  12 (12.00%) high severe

SSIM                    time:   [18.753 ms 18.949 ms 19.175 ms]
                        change: [-22.400% -21.118% -19.844%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) high mild
  1 (1.00%) high severe

MSSSIM                  time:   [20.255 ms 20.784 ms 21.338 ms]
                        change: [-27.431% -25.443% -23.220%] (p = 0.00 < 0.05)
                        Performance has improved.

CIEDE2000               time:   [6.4883 ms 6.5639 ms 6.6424 ms]
                        change: [-84.938% -84.672% -84.445%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  3 (3.00%) high mild

CIEDE2000 #2            time:   [7.5739 ms 7.5937 ms 7.6150 ms]
                        change: [-82.434% -82.214% -82.016%] (p = 0.00 < 0.05)
                        Performance has improved.
```

**Pull request merged**
