### PR TITLE
Implement decoding via ffmpeg

### PR DESCRIPTION
**Pull request by shssoichiro**
This is enabled via a compile-time feature flag,
due to limitations with traits and generic parameters.
Ffmpeg allows the decoding of arbitrary video formats.
The default remains to use the y4m decoder only,
since ffmpeg depends on an external C library.

### CODE REVIEW

**Review by vibhoothiiaanand — COMMENTED** [review]
Amazing, 
Can we split the patch into multiple commits viz, 
+ One for CI change
+ One for readme
+ Split more if necessary, so we can have smaller patches,

**Comment by lu-zero** [comment]
This goes against my effort of moving the decoders in the binary and keep the library just about metrics. Can we try split the two concerns?

**Comment by shssoichiro** [comment]
Yes, I'll see what I can do in regard to moving the decoders out of the library.

**Comment by shssoichiro** [comment]
I moved the decoders to their own crate, exposed the Decoder trait by default (no longer behind a feature), and split the commits in a way that made sense to me. I had to keep the CI changes paired with the addition of ffmpeg, because that is the part that required the CI changes.

**Comment by lu-zero** [comment]
The benchmarks need an update, beside that it is nice :)

**Pull request merged**
